version: "3"
services:
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_USERNAME}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5050:5050
    volumes:
      - "./pgadmin/config/servers.json:/pgadmin4/servers.json"
    depends_on:
      - "postgres"
  postgres:
    image: "postgres:11"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_TARGET_DB
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/config/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - ./postgres/import:/import
volumes:
  postgres_data:
    driver_opts:
      type: tmpfs
      device: tmpfs

