version: "3"
services:
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    volumes:
      - "./resource/servers.json:/pgadmin4/servers.json"
  postgres:
    image: "postgres:11"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54320:5432"
    volumes:
      - ./volumes/datadir:/var/lib/postgresql/data
